name: canaries_project_egm722
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - geopandas
  - pandas
  - cartopy
  - notebook
  - rasterio
  - pyepsg
  - folium
  - os
  - matplotlib.pyplot
  - math
  - rasterstats
  - numpy